### ISSUE TITLE
スクレイピング機能の実装

### ISSUE THREAD

**Issue by toua20001** [toua20001/teppan#4]
- [ ] 過去レース結果を収集する 
- [ ] 競走馬のデータを収集する
- [ ] 収集したデータを管理するDBを構築する
  - [ ] sqlite3で簡素にやる
  - [ ] データモデルを設計する
  - [ ] 設計したデータモデルを実装する
- [ ] テストコードを作成する？
  - [ ] テスト環境の構築が必要…

**Comment by toua20001** [comment]
検索条件をyamlファイルにまとめて検索ファイルを指定して検索する。

```yaml
pid: race_list
start_year: 2020
start_mon: 1
end_year: 2021
end_mon: 12
jyo:
- 01
- 02
- 03
baba:
- 1
- 2
jyoken:
- 1
- 2
barei:
- 11
grade:
- 1
```

```bash
python cli.py scraping serchCondition.yaml
```
